### ISSUE TITLE
docx2pdf - figure resolution is low in resulted pdf

### ISSUE THREAD

**Issue by MaryHe** [ardata-fr/doconv#3]
Hi, firstly thanks very much for the amazing package!

I have a .docx file generated from package officer that contains mostly figures. When I used docx2pdf to convert it to .pdf, the figure resolution in the resulting pdf seems very low. For example, if I use the 'save as' function in WORD directly to save this file as .pdf the file size is 205K and figures look ok. But the .pdf resulted from docx2pdf only has a file size of 130K.

I tried to set the resolution higher in my original .docx file, yet the resulting .pdf still has the same low resolution figures and same file size (130K).

Could you advise possible reasons? Or maybe add functionality that allows control of resolution of the converted .pdf?

Thanks!

**Comment by davidgohel** [comment]
Hi

I don't know the reason. It's fine on macOS so I suspect it happens on Windows. Are you working on a Windows or a macOS machine?

**Comment by MaryHe** [comment]
Hi, thanks for the response. Yes I am working on Windows.

**Comment by MaryHe** [comment]
I think I found something that may solve it, I would appreciate it very much if you can help look into it, as I do not have enough technical knowledge. Looks like the option wdExportOptimizeForPrint instead of wdExportOptimizeForOnScreen, in the PowerShell script, would generate a larger file, which I assume would have higher quality? 
https://learn.microsoft.com/en-us/office/vba/api/word.wdexportoptimizefor

**Comment by davidgohel** [comment]
sure, thank you for that.

I just push an updated version with your fix, could you try please and let me know if it fixes your issue (I don't have Windows available for now)

**Comment by MaryHe** [comment]
Yes it worked! Thank you so much! 
Will this version be pushed to CRAN?

**Comment by davidgohel** [comment]
Thank you for taking time to help!

yes, I'll send it to CRAN in a week or two
