### ISSUE TITLE
'could not convert' error message in docx2pdf is unclear

### ISSUE THREAD

**Issue by daranzolin** [ardata-fr/doconv#6]
This appears to be an ideal package for one of my use cases. However, I and [at least one other user](https://stackoverflow.com/questions/71955204/converting-docx-files-to-pdf-files-with-docx2pdf) am puzzled by the `Error: could not convert` message when using `docx2pdf()`. It would be very helpful if there were some clue as to why the function failed.

**Comment by ms609** [comment]
I've proposed a PR (#7) to surface the underlying error message to the user.

In my cases this reflects my system's execution policies, but I found Microsoft's suggested help page impenetrable.  It'd be helpful if necessary steps could be summarised in this package's documentation.

**Comment by davidgohel** [comment]
thank you @ms609 

Let me know if this should be repopen :)
